name: Android UI Testing CI

on:
  push:
    branches: [ "ci/uitesting", "main" ]
  pull_request:
    branches: [ "ci/uitesting", "main" ]

jobs:
  uitest:
    runs-on: macos-11
  steps:
    - uses: actions/checkout@v3

    - uses: gradle/wrapper-validation-action@v1

    - uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '18'

    - uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-${{ github.job }}-${{ hashFiles('**/*.gradle*') }}-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}-${{ hashFiles('**/buildSrc/**/*.kt') }}
        restore-keys: |
          ${{ runner.os }}-${{ github.job }}-

    - uses: actions/cache@v2
      id: avd-cache
      with:
        path: |
          ~/.android/avd/*
          ~/.android/adb*
        key: avd

    - name: Generate AVD snapshot for caching
      if: steps.avd-cache.outputs.cache-hit != 'true'
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: aosp_atd
        arch: x86
        profile: Galaxy Nexus
        force-avd-creation: false
        emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        disable-animations: false
        channel: canary
        script: echo "Generated AVD snapshot for caching."

    - name: Run Android instrumented tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
        target: aosp_atd
        arch: x86
        profile: Galaxy Nexus
        force-avd-creation: false
        emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
        channel: canary
        script: ./gradlew connectedCheck
